Repository m053m716/nigeLab, pull requests merged in 2020-01, with the labels that each got.

#57 Fix Streams init
  +nigeLab/+defaults/Block.m
  +nigeLab/+defaults/Video.m
  +nigeLab/+libs/@DashBoard/DashBoard.m
  +nigeLab/+libs/@VideosFieldType/VideosFieldType.m
  +nigeLab/+utils/buildWorkerConfigScript.m
  +nigeLab/+utils/checkForWorker.m
  +nigeLab/+utils/getLastDispText.m
  +nigeLab/+utils/initChannelStruct.m
  +nigeLab/+utils/reportProgress.m
  +nigeLab/+utils/shortenedName.m
  +nigeLab/+utils/shortenedPath.m
  +nigeLab/+utils/signal.m
  +nigeLab/+workflow/readMatInfoRC.m
  +nigeLab/@Animal/Animal.m
  +nigeLab/@Animal/init.m
  +nigeLab/@Block/Block.m
  +nigeLab/@Block/getStatus.m
  +nigeLab/@Block/init.m
  +nigeLab/@Block/initChannels.m
  +nigeLab/@Block/initStreams.m
  +nigeLab/@Block/intan2Block.m
  +nigeLab/@Block/linkChannelsField.m
  +nigeLab/@Block/linkStreamsField.m
  +nigeLab/@Block/linkToData.m
  +nigeLab/@Block/parseHeader.m
  +nigeLab/@Block/parseHierarchy.m
  +nigeLab/@Block/private/ReadRHDHeader.m
  +nigeLab/@Block/private/ReadRHSHeader.m
  +nigeLab/@Block/private/ReadTDTHeader.m
  +nigeLab/@Block/splitMultiAnimals.m
  +nigeLab/@Block/tdt2Block.m
  +nigeLab/@Tank/Tank.m
  +nigeLab/@nigelObj/nigelObj.m
Labels: bugfix, enhancement

#58 Improved Mask
  +nigeLab/+defaults/nigelColors.m
  +nigeLab/+evt/treeSelectionChanged.m
  +nigeLab/+libs/@DashBoard/DashBoard.m
  +nigeLab/+libs/@DashBoard/qOperations.m
  +nigeLab/+libs/@SortUI/SortUI.m
  +nigeLab/+libs/@nigelBar/nigelBar.m
  +nigeLab/+libs/@nigelButton/nigelButton.m
  +nigeLab/+libs/@nigelPanel/nigelPanel.m
  +nigeLab/+libs/@nigelProgress/nigelProgress.m
  +nigeLab/+libs/@remoteMonitor/remoteMonitor.m
  +nigeLab/+utils/buildWorkerConfigScript.m
  +nigeLab/+utils/shortenedName.m
  +nigeLab/@Animal/parseProbes.m
  +nigeLab/@Block/Block.m
  +nigeLab/@Block/doAutoClustering.m
  +nigeLab/@Block/doLFPExtraction.m
  +nigeLab/@Block/doReReference.m
  +nigeLab/@Block/doSD.m
  +nigeLab/@Block/doUnitFilter.m
  +nigeLab/@Block/intan2Block.m
  +nigeLab/@Block/list.m
  +nigeLab/@nigelObj/nigelObj.m
Labels: bugfix, enhancement

#64 Bugfix/doAutoClutsering_emptyDiskData
  +nigeLab/+libs/@DiskData/DiskData.m
  +nigeLab/@Block/doAutoClustering.m
  +nigeLab/@Block/getChannelsEventData.m
  +nigeLab/@Block/getSpikes.m
Labels: bugfix

#71 Bugfix/subsref
  +nigeLab/+defaults/Animal.m
  +nigeLab/+defaults/Block.m
  +nigeLab/+defaults/Queue.m
  +nigeLab/+defaults/SD.m
  +nigeLab/+defaults/Shortcuts.m
  +nigeLab/+defaults/Video.m
  +nigeLab/@Animal/Animal.m
  +nigeLab/@Animal/subsref.m
  +nigeLab/@Block/Block.m
  +nigeLab/@Block/private/findGoodCluster.m.old
  +nigeLab/@Block/subsref.m
  +nigeLab/@Tank/Tank.m
  +nigeLab/@Tank/subsref.m
  +nigeLab/@nigelObj/nigelObj.m
  +nigeLab/setup/demo/demo_nigeLab.m
  .gitignore
Labels: bugfix, enhancement, help wanted
